# exclude everything by default to limit context size and cache miss
*
# module definition
!go.*
# internal dependencies
!cannon/
!op-alt-da/
!tw-node/
!op-preimage/
!tw-program/
!tw-service/
!tw-supervisor/

**/bin
**/testdata
**/tests
