# exclude everything by default to limit context size and cache miss
*
# module definition
!go.*
# internal dependencies
!cannon/
!op-alt-da/
!cp-node/
!op-preimage/
!cp-program/
!cp-service/
!cp-supervisor/

**/bin
**/testdata
**/tests
