FROM debian:bookworm-20240812-slim
ENTRYPOINT ["/tw-deployer"]
COPY tw-deployer /tw-deployer

# Install ca-certificates so that HTTPS requests work
RUN apt-get update && apt-get install -y ca-certificates

# Symlink onto the PATH
RUN ln -s /tw-deployer /usr/local/bin/tw-deployer
