FROM debian:bookworm-20240812-slim
ENTRYPOINT ["/rhs-deployer"]
COPY rhs-deployer /rhs-deployer

# Install ca-certificates so that HTTPS requests work
RUN apt-get update && apt-get install -y ca-certificates

# Symlink onto the PATH
RUN ln -s /rhs-deployer /usr/local/bin/rhs-deployer
