# exclude everything by default to limit context size and cache miss
*
# module definition
!go.*
# internal dependencies
!cannon/
!op-alt-da/
!rhs-node/
!op-preimage/
!rhs-program/
!rhs-service/
!rhs-supervisor/

**/bin
**/testdata
**/tests
